In [1]:
import pandas as pd
df=pd.read_csv('train.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"])
df.dropna()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0             60       RL         65.0     8450   Pave      Reg       2003   
1             20       RL         80.0     9600   Pave      Reg       1976   
2             60       RL         68.0    11250   Pave      IR1       2001   
3             70       RL         60.0     9550   Pave      IR1       1915   
4             60       RL         84.0    14260   Pave      IR1       2000   
...          ...      ...          ...      ...    ...      ...        ...   
1455          60       RL         62.0     7917   Pave      Reg       1999   
1456          20       RL         85.0    13175   Pave      Reg       1978   
1457          70       RL         66.0     9042   Pave      Reg       1941   
1458          20       RL         68.0     9717   Pave      Reg       1950   
1459          20       RL         75.0     9937   Pave      Reg       1965   

      1stFlrSF  2ndFlrSF  SalePrice  
0          856       854     208500  
1         1262         0     181500  
2          920       866     223500  
3          961       756     140000  
4         1145      1053     250000  
...        ...       ...        ...  
1455       953       694     175000  
1456      2073         0     210000  
1457      1188      1152     266500  
1458      1078         0     142125  
1459      1256         0     147500  

[1201 rows x 10 columns]

In [2]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'SalePrice'],
      dtype='object')

In [3]:
df.shape

(1460, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1460 non-null   int64  
 1   MSZoning     1460 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1460 non-null   int64  
 4   Street       1460 non-null   object 
 5   LotShape     1460 non-null   object 
 6   YearBuilt    1460 non-null   int64  
 7   1stFlrSF     1460 non-null   int64  
 8   2ndFlrSF     1460 non-null   int64  
 9   SalePrice    1460 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 114.2+ KB


In [5]:
df.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage    259
LotArea          0
Street           0
LotShape         0
YearBuilt        0
1stFlrSF         0
2ndFlrSF         0
SalePrice        0
dtype: int64

In [6]:
for i in df.columns:
    print("features name : {} : and uique values : {}".format(i, len(df[i].unique())))

features name : MSSubClass : and uique values : 15
features name : MSZoning : and uique values : 5
features name : LotFrontage : and uique values : 111
features name : LotArea : and uique values : 1073
features name : Street : and uique values : 2
features name : LotShape : and uique values : 4
features name : YearBuilt : and uique values : 112
features name : 1stFlrSF : and uique values : 753
features name : 2ndFlrSF : and uique values : 417
features name : SalePrice : and uique values : 663


In [7]:
import datetime
datetime.datetime.now().year

df['Total Years']=datetime.datetime.now().year-df['YearBuilt']



In [8]:
df.drop("YearBuilt",axis=1,inplace=True)


In [9]:
cat_features=["MSSubClass", "MSZoning", "Street", "LotShape"]
out_feature="SalePrice"

In [10]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder={}
lbl_encoder["MSSubClass"]=LabelEncoder()
lbl_encoder["MSSubClass"].fit_transform(df['MSSubClass'])

array([5, 0, 5, ..., 6, 0, 0], dtype=int64)

In [11]:
    lb_encoder={}

    for features in cat_features:
        lb_encoder[features]=LabelEncoder()
        df[features]=lb_encoder[features].fit_transform(df[features])

In [12]:
lb_encoder

{'MSSubClass': LabelEncoder(),
 'MSZoning': LabelEncoder(),
 'Street': LabelEncoder(),
 'LotShape': LabelEncoder()}

In [13]:
df.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  Total Years  
0       854     208500           17  
1         0     181500           44  
2       866     223500           19  
3       756     140000          105  
4      1053     250000           20

In [14]:
import numpy as np
cat_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
cat_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [15]:
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [16]:
#### create continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i)

In [17]:
cont_features


['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [18]:
cont_values=np.stack([df[i].values for i in cont_features], 1)
cont_values=torch.tensor(cont_values, dtype=torch.float)
cont_values

tensor([[   65.,  8450.,   856.,   854.,    17.],
        [   80.,  9600.,  1262.,     0.,    44.],
        [   68., 11250.,   920.,   866.,    19.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    79.],
        [   68.,  9717.,  1078.,     0.,    70.],
        [   75.,  9937.,  1256.,     0.,    55.]])

In [19]:
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)


In [20]:
cat_features.shape,cont_values.shape,y.shape


(torch.Size([1460, 4]), torch.Size([1460, 5]), torch.Size([1460, 1]))

In [21]:
len(df['MSSubClass'].unique())


15